name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install flake8 flake8-quotes flake8-isort flake8-print
    - name: Run lint
      run: cd gdstorage && flake8
